name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha 🐍
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: matiasonerb
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando cobrinha 🐍"
          add: "dist/*.svg"
